name: Run the SA gate on a new commit

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-quality-staging:
    runs-on: ubuntu-latest
    name: (STAGING) Datadog Static Analyzer
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: (STAGING) Check code meets quality standards
      id: datadog-static-analysis
      uses: datadog/datadog-static-analyzer-github-action@v1
      with:
        dd_api_key: ${{ secrets.DD_API_KEY_ORG2 }}
        dd_app_key: ${{ secrets.DD_APP_KEY_ORG2 }}
        dd_service: "ci-gates-synthetic-helper"
        dd_env: "testing-github-action"
  datadog-gate-staging:
    needs: check-quality-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
      - name: Checkout datadog-ci
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: DataDog/datadog-ci
          path: datadog-ci
      - name: Change to branch
        run: git checkout juan-fernandez/add-sha-for-pull-requests
        working-directory: datadog-ci
      - name: Install dependencies
        run: yarn
        working-directory: datadog-ci
      - name: Run the gate
        env:
          DD_BETA_COMMANDS_ENABLED: true
          DD_API_KEY: ${{ secrets.DD_API_KEY_ORG2 }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY_ORG2 }}
        run: yarn launch gate evaluate
        working-directory: datadog-ci
