name: Run the SA gate on a new commit

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-quality-prod:
    runs-on: ubuntu-latest
    name: (PROD) Datadog Static Analyzer
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: (PROD) Check code meets quality standards
      id: datadog-static-analysis
      uses: datadog/datadog-static-analyzer-github-action@v1
      with:
        dd_api_key: ${{ secrets.DD_API_KEY_STAGING }}
        dd_app_key: ${{ secrets.DD_APP_KEY_STAGING }}
        dd_service: "ci-gates-synthetic-helper"
        dd_env: "testing-github-action"
        dd_site: "datad0g.com"
  datadog-gate-prod:
    needs: check-quality-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
      - run: yarn global add @datadog/datadog-ci
      - run: >
          DD_BETA_COMMANDS_ENABLED=true
          DD_API_KEY=${{ secrets.DD_API_KEY_STAGING }}
          DD_APP_KEY=${{ secrets.DD_APP_KEY_STAGING }}
          DD_SITE=datad0g.com
          datadog-ci gate evaluate
